version: '3.8'

services:
  frontend:
    restart: always
    image: react-frontend:v4
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - frontend-backend

  backend:
    restart: always
    image: spring-backend:v4
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=database
    networks:
      - frontend-backend

  database:
    restart: always
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Branajay
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - frontend-backend

networks:
  frontend-backend:
    driver: bridge
